import * as React from 'react'

import Icon from '../Icon'

export type Country = {
  flag?: React.FunctionComponent<{}>
  name: string
  iso2Code: string
  dialCode: string
  areaCodes: string[]
  order?: number
}

export default [
  { name: 'Afghanistan (‫افغانستان‬‎)', iso2Code: 'af', dialCode: '93' },
  { name: 'Albania (Shqipëri)', iso2Code: 'al', dialCode: '355' },
  { name: 'Algeria (‫الجزائر‬‎)', iso2Code: 'dz', dialCode: '213' },
  { name: 'American Samoa', iso2Code: 'as', dialCode: '1', order: 5 },
  { name: 'Andorra', iso2Code: 'ad', dialCode: '376' },
  { name: 'Angola', iso2Code: 'ao', dialCode: '244' },
  { name: 'Anguilla', iso2Code: 'ai', dialCode: '1', order: 6 },
  { name: 'Antigua and Barbuda', iso2Code: 'ag', dialCode: '1', order: 7 },
  { name: 'Argentina', iso2Code: 'ar', dialCode: '54' },
  { name: 'Armenia (Հայաստան)', iso2Code: 'am', dialCode: '374' },
  { name: 'Aruba', iso2Code: 'aw', dialCode: '297' },
  { name: 'Australia', iso2Code: 'au', dialCode: '61', order: 0 },
  { name: 'Austria (Österreich)', iso2Code: 'at', dialCode: '43' },
  { name: 'Azerbaijan (Azərbaycan)', iso2Code: 'az', dialCode: '994' },
  { name: 'Bahamas', iso2Code: 'bs', dialCode: '1', order: 8 },
  { name: 'Bahrain (‫البحرين‬‎)', iso2Code: 'bh', dialCode: '973' },
  { name: 'Bangladesh (বাংলাদেশ)', iso2Code: 'bd', dialCode: '880' },
  { name: 'Barbados', iso2Code: 'bb', dialCode: '1', order: 9 },
  { name: 'Belarus (Беларусь)', iso2Code: 'by', dialCode: '375' },
  { name: 'Belgium (België)', iso2Code: 'be', dialCode: '32' },
  { name: 'Belize', iso2Code: 'bz', dialCode: '501' },
  { name: 'Benin (Bénin)', iso2Code: 'bj', dialCode: '229' },
  { name: 'Bermuda', iso2Code: 'bm', dialCode: '1', order: 10 },
  { name: 'Bhutan (འབྲུག)', iso2Code: 'bt', dialCode: '975' },
  { name: 'Bolivia', iso2Code: 'bo', dialCode: '591' },
  {
    name: 'Bosnia and Herzegovina (Босна и Херцеговина)',
    iso2Code: 'ba',
    dialCode: '387',
  },
  { name: 'Botswana', iso2Code: 'bw', dialCode: '267' },
  { name: 'Brazil (Brasil)', iso2Code: 'br', dialCode: '55' },
  { name: 'British Indian Ocean Territory', iso2Code: 'io', dialCode: '246' },
  { name: 'British Virgin Islands', iso2Code: 'vg', dialCode: '1', order: 11 },
  { name: 'Brunei', iso2Code: 'bn', dialCode: '673' },
  { name: 'Bulgaria (България)', iso2Code: 'bg', dialCode: '359' },
  { name: 'Burkina Faso', iso2Code: 'bf', dialCode: '226' },
  { name: 'Burundi (Uburundi)', iso2Code: 'bi', dialCode: '257' },
  { name: 'Cambodia (កម្ពុជា)', iso2Code: 'kh', dialCode: '855' },
  { name: 'Cameroon (Cameroun)', iso2Code: 'cm', dialCode: '237' },
  { name: 'Canada', iso2Code: 'ca', dialCode: '1', order: 1 },
  { name: 'Cape Verde (Kabu Verdi)', iso2Code: 'cv', dialCode: '238' },
  { name: 'Caribbean Netherlands', iso2Code: 'bq', dialCode: '599', order: 1 },
  { name: 'Cayman Islands', iso2Code: 'ky', dialCode: '1', order: 12 },
  {
    name: 'Central African Republic (République centrafricaine)',
    iso2Code: 'cf',
    dialCode: '236',
  },
  { name: 'Chad (Tchad)', iso2Code: 'td', dialCode: '235' },
  { name: 'Chile', iso2Code: 'cl', dialCode: '56' },
  { name: 'China (中国)', iso2Code: 'cn', dialCode: '86' },
  { name: 'Christmas Island', iso2Code: 'cx', dialCode: '61', order: 2 },
  { name: 'Cocos (Keeling) Islands', iso2Code: 'cc', dialCode: '61', order: 1 },
  { name: 'Colombia', iso2Code: 'co', dialCode: '57' },
  { name: 'Comoros (‫جزر القمر‬‎)', iso2Code: 'km', dialCode: '269' },
  {
    name: 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)',
    iso2Code: 'cd',
    dialCode: '243',
  },
  {
    name: 'Congo (Republic) (Congo-Brazzaville)',
    iso2Code: 'cg',
    dialCode: '242',
  },
  { name: 'Cook Islands', iso2Code: 'ck', dialCode: '682' },
  { name: 'Costa Rica', iso2Code: 'cr', dialCode: '506' },
  { name: 'Côte d’Ivoire', iso2Code: 'ci', dialCode: '225' },
  { name: 'Croatia (Hrvatska)', iso2Code: 'hr', dialCode: '385' },
  { name: 'Cuba', iso2Code: 'cu', dialCode: '53' },
  { name: 'Curaçao', iso2Code: 'cw', dialCode: '599', order: 0 },
  { name: 'Cyprus (Κύπρος)', iso2Code: 'cy', dialCode: '357' },
  { name: 'Czech Republic (Česká republika)', iso2Code: 'cz', dialCode: '420' },
  { name: 'Denmark (Danmark)', iso2Code: 'dk', dialCode: '45' },
  { name: 'Djibouti', iso2Code: 'dj', dialCode: '253' },
  { name: 'Dominica', iso2Code: 'dm', dialCode: '1', order: 13 },
  {
    name: 'Dominican Republic (República Dominicana)',
    iso2Code: 'do',
    dialCode: '1',
    order: 2,
  },
  { name: 'Ecuador', iso2Code: 'ec', dialCode: '593' },
  { name: 'Egypt (‫مصر‬‎)', iso2Code: 'eg', dialCode: '20' },
  { name: 'El Salvador', iso2Code: 'sv', dialCode: '503' },
  {
    name: 'Equatorial Guinea (Guinea Ecuatorial)',
    iso2Code: 'gq',
    dialCode: '240',
  },
  { name: 'Eritrea', iso2Code: 'er', dialCode: '291' },
  { name: 'Estonia (Eesti)', iso2Code: 'ee', dialCode: '372' },
  { name: 'Ethiopia', iso2Code: 'et', dialCode: '251' },
  {
    name: 'Falkland Islands (Islas Malvinas)',
    iso2Code: 'fk',
    dialCode: '500',
  },
  { name: 'Faroe Islands (Føroyar)', iso2Code: 'fo', dialCode: '298' },
  { name: 'Fiji', iso2Code: 'fj', dialCode: '679' },
  { name: 'Finland (Suomi)', iso2Code: 'fi', dialCode: '358', order: 0 },
  {
    name: 'France',
    iso2Code: 'fr',
    dialCode: '33',
    flag: () => <Icon colored icon="flag-france" />,
  },
  { name: 'French Guiana (Guyane française)', iso2Code: 'gf', dialCode: '594' },
  {
    name: 'French Polynesia (Polynésie française)',
    iso2Code: 'pf',
    dialCode: '689',
  },
  { name: 'Gabon', iso2Code: 'ga', dialCode: '241' },
  { name: 'Gambia', iso2Code: 'gm', dialCode: '220' },
  { name: 'Georgia (საქართველო)', iso2Code: 'ge', dialCode: '995' },
  { name: 'Germany (Deutschland)', iso2Code: 'de', dialCode: '49' },
  { name: 'Ghana (Gaana)', iso2Code: 'gh', dialCode: '233' },
  { name: 'Gibraltar', iso2Code: 'gi', dialCode: '350' },
  { name: 'Greece (Ελλάδα)', iso2Code: 'gr', dialCode: '30' },
  { name: 'Greenland (Kalaallit Nunaat)', iso2Code: 'gl', dialCode: '299' },
  { name: 'Grenada', iso2Code: 'gd', dialCode: '1', order: 14 },
  { name: 'Guadeloupe', iso2Code: 'gp', dialCode: '590', order: 0 },
  { name: 'Guam', iso2Code: 'gu', dialCode: '1', order: 15 },
  { name: 'Guatemala', iso2Code: 'gt', dialCode: '502' },
  { name: 'Guernsey', iso2Code: 'gg', dialCode: '44', order: 1 },
  { name: 'Guinea (Guinée)', iso2Code: 'gn', dialCode: '224' },
  { name: 'Guinea-Bissau (Guiné Bissau)', iso2Code: 'gw', dialCode: '245' },
  { name: 'Guyana', iso2Code: 'gy', dialCode: '592' },
  { name: 'Haiti', iso2Code: 'ht', dialCode: '509' },
  { name: 'Honduras', iso2Code: 'hn', dialCode: '504' },
  { name: 'Hong Kong (香港)', iso2Code: 'hk', dialCode: '852' },
  { name: 'Hungary (Magyarország)', iso2Code: 'hu', dialCode: '36' },
  { name: 'Iceland (Ísland)', iso2Code: 'is', dialCode: '354' },
  { name: 'India (भारत)', iso2Code: 'in', dialCode: '91' },
  { name: 'Indonesia', iso2Code: 'id', dialCode: '62' },
  { name: 'Iran (‫ایران‬‎)', iso2Code: 'ir', dialCode: '98' },
  { name: 'Iraq (‫العراق‬‎)', iso2Code: 'iq', dialCode: '964' },
  { name: 'Ireland', iso2Code: 'ie', dialCode: '353' },
  { name: 'Isle of Man', iso2Code: 'im', dialCode: '44', order: 2 },
  { name: 'Israel (‫ישראל‬‎)', iso2Code: 'il', dialCode: '972' },
  { name: 'Italy (Italia)', iso2Code: 'it', dialCode: '39', order: 0 },
  { name: 'Jamaica', iso2Code: 'jm', dialCode: '1', order: 4 },
  { name: 'Japan (日本)', iso2Code: 'jp', dialCode: '81' },
  { name: 'Jersey', iso2Code: 'je', dialCode: '44', order: 3 },
  { name: 'Jordan (‫الأردن‬‎)', iso2Code: 'jo', dialCode: '962' },
  { name: 'Kazakhstan (Казахстан)', iso2Code: 'kz', dialCode: '7', order: 1 },
  { name: 'Kenya', iso2Code: 'ke', dialCode: '254' },
  { name: 'Kiribati', iso2Code: 'ki', dialCode: '686' },
  { name: 'Kosovo', iso2Code: 'xk', dialCode: '383' },
  { name: 'Kuwait (‫الكويت‬‎)', iso2Code: 'kw', dialCode: '965' },
  { name: 'Kyrgyzstan (Кыргызстан)', iso2Code: 'kg', dialCode: '996' },
  { name: 'Laos (ລາວ)', iso2Code: 'la', dialCode: '856' },
  { name: 'Latvia (Latvija)', iso2Code: 'lv', dialCode: '371' },
  { name: 'Lebanon (‫لبنان‬‎)', iso2Code: 'lb', dialCode: '961' },
  { name: 'Lesotho', iso2Code: 'ls', dialCode: '266' },
  { name: 'Liberia', iso2Code: 'lr', dialCode: '231' },
  { name: 'Libya (‫ليبيا‬‎)', iso2Code: 'ly', dialCode: '218' },
  { name: 'Liechtenstein', iso2Code: 'li', dialCode: '423' },
  { name: 'Lithuania (Lietuva)', iso2Code: 'lt', dialCode: '370' },
  { name: 'Luxembourg', iso2Code: 'lu', dialCode: '352' },
  { name: 'Macau (澳門)', iso2Code: 'mo', dialCode: '853' },
  { name: 'Macedonia (FYROM) (Македонија)', iso2Code: 'mk', dialCode: '389' },
  { name: 'Madagascar (Madagasikara)', iso2Code: 'mg', dialCode: '261' },
  { name: 'Malawi', iso2Code: 'mw', dialCode: '265' },
  { name: 'Malaysia', iso2Code: 'my', dialCode: '60' },
  { name: 'Maldives', iso2Code: 'mv', dialCode: '960' },
  { name: 'Mali', iso2Code: 'ml', dialCode: '223' },
  { name: 'Malta', iso2Code: 'mt', dialCode: '356' },
  { name: 'Marshall Islands', iso2Code: 'mh', dialCode: '692' },
  { name: 'Martinique', iso2Code: 'mq', dialCode: '596' },
  { name: 'Mauritania (‫موريتانيا‬‎)', iso2Code: 'mr', dialCode: '222' },
  { name: 'Mauritius (Moris)', iso2Code: 'mu', dialCode: '230' },
  { name: 'Mayotte', iso2Code: 'yt', dialCode: '262', order: 1 },
  { name: 'Mexico (México)', iso2Code: 'mx', dialCode: '52' },
  { name: 'Micronesia', iso2Code: 'fm', dialCode: '691' },
  { name: 'Moldova (Republica Moldova)', iso2Code: 'md', dialCode: '373' },
  { name: 'Monaco', iso2Code: 'mc', dialCode: '377' },
  { name: 'Mongolia (Монгол)', iso2Code: 'mn', dialCode: '976' },
  { name: 'Montenegro (Crna Gora)', iso2Code: 'me', dialCode: '382' },
  { name: 'Montserrat', iso2Code: 'ms', dialCode: '1', order: 16 },
  { name: 'Morocco (‫المغرب‬‎)', iso2Code: 'ma', dialCode: '212', order: 0 },
  { name: 'Mozambique (Moçambique)', iso2Code: 'mz', dialCode: '258' },
  { name: 'Myanmar (Burma) (မြန်မာ)', iso2Code: 'mm', dialCode: '95' },
  { name: 'Namibia (Namibië)', iso2Code: 'na', dialCode: '264' },
  { name: 'Nauru', iso2Code: 'nr', dialCode: '674' },
  { name: 'Nepal (नेपाल)', iso2Code: 'np', dialCode: '977' },
  { name: 'Netherlands (Nederland)', iso2Code: 'nl', dialCode: '31' },
  {
    name: 'New Caledonia (Nouvelle-Calédonie)',
    iso2Code: 'nc',
    dialCode: '687',
  },
  { name: 'New Zealand', iso2Code: 'nz', dialCode: '64' },
  { name: 'Nicaragua', iso2Code: 'ni', dialCode: '505' },
  { name: 'Niger (Nijar)', iso2Code: 'ne', dialCode: '227' },
  { name: 'Nigeria', iso2Code: 'ng', dialCode: '234' },
  { name: 'Niue', iso2Code: 'nu', dialCode: '683' },
  { name: 'Norfolk Island', iso2Code: 'nf', dialCode: '672' },
  {
    name: 'North Korea (조선 민주주의 인민 공화국)',
    iso2Code: 'kp',
    dialCode: '850',
  },
  {
    name: 'Northern Mariana Islands',
    iso2Code: 'mp',
    dialCode: '1',
    order: 17,
  },
  { name: 'Norway (Norge)', iso2Code: 'no', dialCode: '47', order: 0 },
  { name: 'Oman (‫عُمان‬‎)', iso2Code: 'om', dialCode: '968' },
  { name: 'Pakistan (‫پاکستان‬‎)', iso2Code: 'pk', dialCode: '92' },
  { name: 'Palau', iso2Code: 'pw', dialCode: '680' },
  { name: 'Palestine (‫فلسطين‬‎)', iso2Code: 'ps', dialCode: '970' },
  { name: 'Panama (Panamá)', iso2Code: 'pa', dialCode: '507' },
  { name: 'Papua New Guinea', iso2Code: 'pg', dialCode: '675' },
  { name: 'Paraguay', iso2Code: 'py', dialCode: '595' },
  { name: 'Peru (Perú)', iso2Code: 'pe', dialCode: '51' },
  { name: 'Philippines', iso2Code: 'ph', dialCode: '63' },
  { name: 'Poland (Polska)', iso2Code: 'pl', dialCode: '48' },
  { name: 'Portugal', iso2Code: 'pt', dialCode: '351' },
  { name: 'Puerto Rico', iso2Code: 'pr', dialCode: '1', order: 3 },
  { name: 'Qatar (‫قطر‬‎)', iso2Code: 'qa', dialCode: '974' },
  { name: 'Réunion (La Réunion)', iso2Code: 're', dialCode: '262', order: 0 },
  { name: 'Romania (România)', iso2Code: 'ro', dialCode: '40' },
  { name: 'Russia (Россия)', iso2Code: 'ru', dialCode: '7', order: 0 },
  { name: 'Rwanda', iso2Code: 'rw', dialCode: '250' },
  { name: 'Saint Barthélemy', iso2Code: 'bl', dialCode: '590', order: 1 },
  { name: 'Saint Helena', iso2Code: 'sh', dialCode: '290' },
  { name: 'Saint Kitts and Nevis', iso2Code: 'kn', dialCode: '1', order: 18 },
  { name: 'Saint Lucia', iso2Code: 'lc', dialCode: '1', order: 19 },
  {
    name: 'Saint Martin (Saint-Martin (partie française))',
    iso2Code: 'mf',
    dialCode: '590',
    order: 2,
  },
  {
    name: 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)',
    iso2Code: 'pm',
    dialCode: '508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    iso2Code: 'vc',
    dialCode: '1',
    order: 20,
  },
  { name: 'Samoa', iso2Code: 'ws', dialCode: '685' },
  { name: 'San Marino', iso2Code: 'sm', dialCode: '378' },
  {
    name: 'São Tomé and Príncipe (São Tomé e Príncipe)',
    iso2Code: 'st',
    dialCode: '239',
  },
  {
    name: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)',
    iso2Code: 'sa',
    dialCode: '966',
  },
  { name: 'Senegal (Sénégal)', iso2Code: 'sn', dialCode: '221' },
  { name: 'Serbia (Србија)', iso2Code: 'rs', dialCode: '381' },
  { name: 'Seychelles', iso2Code: 'sc', dialCode: '248' },
  { name: 'Sierra Leone', iso2Code: 'sl', dialCode: '232' },
  { name: 'Singapore', iso2Code: 'sg', dialCode: '65' },
  { name: 'Sint Maarten', iso2Code: 'sx', dialCode: '1', order: 21 },
  { name: 'Slovakia (Slovensko)', iso2Code: 'sk', dialCode: '421' },
  { name: 'Slovenia (Slovenija)', iso2Code: 'si', dialCode: '386' },
  { name: 'Solomon Islands', iso2Code: 'sb', dialCode: '677' },
  { name: 'Somalia (Soomaaliya)', iso2Code: 'so', dialCode: '252' },
  { name: 'South Africa', iso2Code: 'za', dialCode: '27' },
  { name: 'South Korea (대한민국)', iso2Code: 'kr', dialCode: '82' },
  { name: 'South Sudan (‫جنوب السودان‬‎)', iso2Code: 'ss', dialCode: '211' },
  { name: 'Spain (España)', iso2Code: 'es', dialCode: '34' },
  { name: 'Sri Lanka (ශ්‍රී ලංකාව)', iso2Code: 'lk', dialCode: '94' },
  { name: 'Sudan (‫السودان‬‎)', iso2Code: 'sd', dialCode: '249' },
  { name: 'Suriname', iso2Code: 'sr', dialCode: '597' },
  { name: 'Svalbard and Jan Mayen', iso2Code: 'sj', dialCode: '47', order: 1 },
  { name: 'Swaziland', iso2Code: 'sz', dialCode: '268' },
  { name: 'Sweden (Sverige)', iso2Code: 'se', dialCode: '46' },
  { name: 'Switzerland (Schweiz)', iso2Code: 'ch', dialCode: '41' },
  { name: 'Syria (‫سوريا‬‎)', iso2Code: 'sy', dialCode: '963' },
  { name: 'Taiwan (台灣)', iso2Code: 'tw', dialCode: '886' },
  { name: 'Tajikistan', iso2Code: 'tj', dialCode: '992' },
  { name: 'Tanzania', iso2Code: 'tz', dialCode: '255' },
  { name: 'Thailand (ไทย)', iso2Code: 'th', dialCode: '66' },
  { name: 'Timor-Leste', iso2Code: 'tl', dialCode: '670' },
  { name: 'Togo', iso2Code: 'tg', dialCode: '228' },
  { name: 'Tokelau', iso2Code: 'tk', dialCode: '690' },
  { name: 'Tonga', iso2Code: 'to', dialCode: '676' },
  { name: 'Trinidad and Tobago', iso2Code: 'tt', dialCode: '1', order: 22 },
  { name: 'Tunisia (‫تونس‬‎)', iso2Code: 'tn', dialCode: '216' },
  { name: 'Turkey (Türkiye)', iso2Code: 'tr', dialCode: '90' },
  { name: 'Turkmenistan', iso2Code: 'tm', dialCode: '993' },
  {
    name: 'Turks and Caicos Islands',
    iso2Code: 'tc',
    dialCode: '1',
    order: 23,
  },
  { name: 'Tuvalu', iso2Code: 'tv', dialCode: '688' },
  { name: 'U.S. Virgin Islands', iso2Code: 'vi', dialCode: '1', order: 24 },
  { name: 'Uganda', iso2Code: 'ug', dialCode: '256' },
  { name: 'Ukraine (Україна)', iso2Code: 'ua', dialCode: '380' },
  {
    name: 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)',
    iso2Code: 'ae',
    dialCode: '971',
  },
  { name: 'United Kingdom', iso2Code: 'gb', dialCode: '44', order: 0 },
  { name: 'United States', iso2Code: 'us', dialCode: '1', order: 0 },
  { name: 'Uruguay', iso2Code: 'uy', dialCode: '598' },
  { name: 'Uzbekistan (Oʻzbekiston)', iso2Code: 'uz', dialCode: '998' },
  { name: 'Vanuatu', iso2Code: 'vu', dialCode: '678' },
  {
    name: 'Vatican City (Città del Vaticano)',
    iso2Code: 'va',
    dialCode: '39',
    order: 1,
  },
  { name: 'Venezuela', iso2Code: 've', dialCode: '58' },
  { name: 'Vietnam (Việt Nam)', iso2Code: 'vn', dialCode: '84' },
  {
    name: 'Wallis and Futuna (Wallis-et-Futuna)',
    iso2Code: 'wf',
    dialCode: '681',
  },
  {
    name: 'Western Sahara (‫الصحراء الغربية‬‎)',
    iso2Code: 'eh',
    dialCode: '212',
    order: 1,
  },
  { name: 'Yemen (‫اليمن‬‎)', iso2Code: 'ye', dialCode: '967' },
  { name: 'Zambia', iso2Code: 'zm', dialCode: '260' },
  { name: 'Zimbabwe', iso2Code: 'zw', dialCode: '263' },
  { name: 'Åland Islands', iso2Code: 'ax', dialCode: '358', order: 1 },
] as Country[]
